version: "1"
services:
  db:
    image: mongo:latest
    volumes:
        - database:/data/db
    ports:
        - 28000:27017
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 8000:80
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 9000:8089
volumes:
  database:
    

